---
- name: Prepare the DO declaration from the template
  template: src="{{ role_path }}/files/{{ do_declaration_template }}" dest="{{ tmp_dir }}/{{ do_declaration_template }}"

- name: Get BIG-IP Authentication Token from BIG-IP
  uri:
    body: '{"username":"{{ bigip_provider.user}}","password":"{{ bigip_provider.password}}","loginProviderName":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{ bigip_provider.server }}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: "{{ bigip_validate_certs }}"
  register: bigip_auth_response
  retries: 30
  delay: 5
  until: "(bigip_auth_response | success) and (bigip_auth_response.status == 200)"

- name: Use Declarative Onboarding to Async configure BIG-IP
  uri:
    body: "{{ lookup('file','{{ tmp_dir }}/{{ do_declaration_template }}') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{bigip_auth_response.json.token.token}}"
    method: POST
    status_code: 202
    url: "https://{{ bigip_provider.server }}/mgmt/shared/declarative-onboarding"
    validate_certs: "{{ bigip_validate_certs }}"

- name: Wait for Declarative Onboarding to finish up
  uri:
    url: "https://{{ bigip_provider.server }}/mgmt/shared/declarative-onboarding"
    status_code: 200
    headers:
      X-F5-Auth-Token: "{{bigip_auth_response.json.token.token}}"
    validate_certs: "{{ bigip_validate_certs }}"
  register: result
  until: result.status == 200
  retries: 20
  delay: 10

- name: Deploy common AS3 objects for use by Telemetry Streaming
  bigip_appsvcs_extension:
    content: "{{ lookup('file', '{{ as3_ts_dependencies_declaration }}') }}"
    state: present
    provider: "{{ bigip_provider }}"
    validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost


- name: Prepare the AS3 declaration from the template
  template: src="{{ role_path }}/files/{{ as3_app_declaration_template }}" dest="{{ tmp_dir }}/{{ app_tenant }}.json"

- name: Deploy an app service configuration
  bigip_appsvcs_extension:
    content: "{{ lookup('file', '{{ tmp_dir }}/{{ app_tenant }}.json') }}"
    state: present
    provider: "{{ bigip_provider }}"
    validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost


- name: Prepare the Telemetry Streaming declaration from the template
  template: src="{{ role_path }}/files/{{ ts_declaration_template }}" dest="{{ tmp_dir }}/{{ ts_declaration_template }}"


- name: Use Telemetry Streaming to configure BIG-IP
  uri:
    body: "{{ lookup('file','{{ tmp_dir }}/{{ ts_declaration_template }}') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{bigip_auth_response.json.token.token}}"
    method: POST
    status_code: 200
    url: "https://{{ bigip_provider.server }}/mgmt/shared/telemetry/declare"
    validate_certs: "{{ bigip_validate_certs }}"

- name: Destroy an API token
  uri:
    url: "https://{{ bigip_provider.server }}/mgmt/shared/authz/tokens/{{ auth['json']['token']['name'] }}"
    method: DELETE
    headers:
      X-F5-Auth-Token: "{{bigip_auth_response.json.token.token}}"
    status_code: 200
    validate_certs: "{{ bigip_validate_certs }}"
  register: bigip_auth_response