---
- name: Get latest DO and checksum file download urls
  uri:
    url: https://api.github.com/repos/F5Networks/f5-declarative-onboarding/releases/latest
    return_content: yes
    status_code: 200
  register: do_github_releases
- set_fact:
    # weird workaround below: https://github.com/ansible/ansible/issues/27299
    do_latest_release_url: "{{ do_github_releases.json | to_json | from_json | json_query('assets[?ends_with(name, `.rpm`)] | [0] | browser_download_url') }}"
    do_latest_release_checksum_url: "{{ do_github_releases.json | to_json | from_json | json_query('assets[?ends_with(name, `.sha256`)] | [0] | browser_download_url') }}"

- name: Download DO checksum file (sha256)
  get_url:
    url: "{{ do_latest_release_checksum_url }}"
    dest: "{{ tmp_dir }}/{{ do_file_sha256 }}"
    force: yes

- name: Set DO checksum var
  set_fact:
    do_checksum: "{{ lookup('file', '{{ tmp_dir }}/{{ do_file_sha256 }}') | regex_search('^(\\S*)') }}"

- name: Download latest DO RPM file with check (sha256)
  get_url:
    url: "{{ do_latest_release_url }}"
    dest: "{{ tmp_dir }}/{{ do_file }}"
    checksum: "sha256:{{ do_checksum }}"
    force: yes


- name: Add an iAppLX Package for Declarative Onboarding
  bigip_lx_package:
    package: "{{ tmp_dir }}/{{ do_file }}"
    provider: "{{ bigip_provider }}"
    state: present
    validate_certs: no
