---
- name: Create the tmp folder of does not exist
  file: path={{ tmp_dir }} state=directory mode=0755

- name: Download and Install AS3
  import_tasks: install-as3.yml

- name: Download and Install DO
  import_tasks: install-do.yml

- name: Download and Install TS
  import_tasks: install-ts.yml

- name: Configure BIG-IP
  import_tasks: configure-big-ip.yml
