bigip_provider:
  server: "{{ inventory_hostname }}"
  user: admin
  password: admin

bigip_validate_certs: no
bigip_domain: "us-west-2.compute.internal"
bigip_hostname: "ip-{{ inventory_hostname | replace('.', '-')}}.{{ bigip_domain }}"
bigip_ntp_server: "\"0.pool.ntp.org\", \"1.pool.ntp.org\""
bigip_ntp_timezone: "America/Los_Angeles"
bigip_dns_server: "\"10.1.255.254\""
bigip_dns_search: "\"{{ bigip_domain }}\""
bigip_external_self_ip: "10.1.10.241/24"
bigip_internal_self_ip: "10.1.20.241/24"

app_virtual_address: "10.1.10.20"

# TODO: fix DRY problem. This variable is repeated in the other host_vars file
app_server_address: "10.1.20.11"