---
- name: Wait for ElasticSearch to come up before configuring it
  uri:
    url: "{{ elasticsearch_base_url }}/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 20
  delay: 5

- name: Check if ElasticSearch index exists
  uri:
    url: "{{ elasticsearch_base_url }}/{{ elasticsearch_index }}"
    method: GET
    status_code:
      - 200
      - 404
  register: index_check

- debug:
    var: index_check
    verbosity: 2

- name: Set ElasticSearch Index settings
  uri:
    url: "{{ elasticsearch_base_url }}/{{ elasticsearch_index }}"
    method: PUT
    body: "{{ lookup('file','./files/elasticsearch/index-settings.json') }}"
    status_code: 200
    body_format: json
  when: index_check.status == 404

- name: ElasticSearch Mappings settings
  uri:
    url: "{{ elasticsearch_base_url }}/{{ elasticsearch_index }}/_mapping"
    method: PUT
    body: "{{ lookup('file','./files/elasticsearch/mappings-settings.json') }}"
    status_code: 200
    body_format: json
