---
- name: check that docker is running
  import_tasks: docker-containers.yml

- name: Configure Elasticsearch
  import_tasks: elasticsearch.yml

- name: Configure Grafana
  import_tasks: grafana.yml
